theme: jekyll-theme-minimal
title: Taiwan Kotlin User Group
description: Taiwan Kotlin User Group 的網站，在台灣推廣 Kotlin 程式語言，舉辦 Kotlin 相關活動
logo: logo.png
page:
  header:
    og_image: logo.png
locale: zh_Hant_TW
image:
  path: logo.png
  height: 256
  width: 256
google_analytics: UA-78953126-4
kramdown:
  syntax_highlighter: rouge
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-image-size
