theme: jekyll-theme-minimal
canonical_url: 'https://taiwan-kotlin-user-group.github.io/'
title: Taiwan Kotlin User Group
tagline: Kotlin 愛好者的集散地
description: Taiwan Kotlin User Group 的網站，在台灣推廣 Kotlin 程式語言，舉辦相關活動。如果對 Kotlin 有興趣，想要多瞭解一些，歡迎來我們的社群一起聚會！
logo:
  path: logo.png
  height: 256
  width: 256
type: website
page:
  header:
    og_image: logo.png
locale: zh_Hant_TW
image:
  path: logo.png
  height: 256
  width: 256
google_analytics: UA-78953126-4
kramdown:
  syntax_highlighter: rouge
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
defaults:
  - scope:
      path: ""
    values:
      image: /logo.png
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-image-size
